# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 973ee92635bc2c593ea2d6405151d1d20c97388961d56ac3808a8a24646156ae4dc0b202612cea40d2b7bbee32a69ff5117e7fa05b7ff796660a1621b5611fce

test:
  secret_key_base: 81eac1a25f630ee487607e7f91f5ae4e4442c347f2f9af500ee1cb00a2d69aa6b0eff32b0bc88a1e410c27e1e6c43afe43f1917ce00a05d8d471377c5b621612

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
